### ISSUE TITLE
Number of load cells

### ISSUE THREAD

**Issue by danpowell88** [Skaronator/ESP8266-Load-Cell#1]
Are you using a single load cell or multiple?

**Comment by Skaronator** [comment]
Sorry for the late response! I didn't got a E-Mail or missed it...

I'm using 4 loadcells on a single HX711. Here is the wiring diagram:

![image](https://user-images.githubusercontent.com/2886913/41814773-0a13f98e-7758-11e8-80b0-998e1e671d6d.png)
