### ISSUE TITLE
Connection Photos

### ISSUE THREAD

**Issue by bachoo786** [Skaronator/ESP8266-Load-Cell#4]
Hello

Can you please show the connection of the load cells to the load cell sensor as well as to the Wemos?

Thank you.

**Comment by Skaronator** [comment]
Hey,

did you saw the image in #1? The HX711 is via Pin D3 and D4:


https://github.com/Skaronator/ESP8266-Load-Cell/blob/ea1dd6d372639417d1c046c552d9748194dad7fe/code/config.h#L37-L38

Here is the best image I could get without unpluging it :p


![img_20180831_230703](https://user-images.githubusercontent.com/2886913/44935915-e1bdf600-ad72-11e8-8044-9544449b891c.jpg)

**Comment by Skaronator** [comment]
If you have more questions, feel free to comment below.

**Comment by bachoo786** [comment]
hey @Skaronator didnt realize that you had replied.

I tried to upload the code to my esp8266 board but it gives an error saying pin D3 and D4 have not been defined in config.h ? I thought they were already pre-defined? 

Thanks.

**Comment by bachoo786** [comment]
Hi thanks for the reply 
I mounted the load sensors on my bed 4 of them but the weight is not distributed on the mattress as the sensor does not detect the weight until pressured is applied on it i.e. on the side of the bed.

Do you have any idea what could be wrong?
